name: Crowdin (pull)

on:
  schedule:
    - cron: '0 7 * * MON' # every monday at 7 am
  workflow_dispatch:

concurrency:
  group: i18n-management

jobs:
  pull_translations:
    name: 'Pull translations from Crowdin'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: i18n-pull:${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Download translations from Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          push_translations: false
          create_pull_request: false
          crowdin_branch_name: '[${{ github.repository_owner }}.${{ github.event.repository.name }}] main'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Fix broken permissions
        shell: bash
        run: sudo chown -R $USER:$USER .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'New translations from Crowdin'
          commit-message: 'New translations from Crowdin'
          body-path: .github/templates/crowdin-pr.md
          branch: crowdin-pull/main
          labels: sync
          token: ${{ secrets.GITHUB_TOKEN }}
